[project]
name = "ai-research-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sundar Abbas", email = "chughtaiabbas486@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.7",
    "python-dotenv>=1.2.4",
    "streamlit>=1.65.0",
    "tavily-python>=0.8.5",
]

[project.scripts]
ai-research-assistant = "ai_research_assistant:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
